### ISSUE TITLE
ValueError: 'expected exactly one part'

### ISSUE THREAD

**Issue by elpaso** [FlightDataServices/soapfish#40] opened 2018-10-05 10:53 UTC
Hi is there any to remove this limitation?

ValueError: ('expected exactly one part', 'richiesta_RichiestaRispostaSincrona_FornituraIncrementaleOggettiTerreni_Msg', [<soapfish.wsdl11.Part object at 0x7f9cfbc08a90>, <soapfish.wsdl11.Part object at 0x7f9cfbc08ad0>, <soapfish.wsdl11.Part object at 0x7f9cfbc08b10>])

**Comment by pope1ni** [comment] 2020-11-18 09:39
Duplicate of soapteam/soapfish#75.

**Closed by pope1ni** 2020-11-18 09:39 UTC
